### ISSUE TITLE
Add a option in nextcloud parameter for choose the key word to use

### ISSUE THREAD

**Issue by Ludovicis** [jancborchardt/unsplash#12]
Hello jancborchardt ,

Can you add a option in nextcloud parameter for choose the key word to use, please ?
example: car, sun...
Not only for nature

Thanks,

**Comment by jancborchardt** [comment]
Hi @ludovicis :)
I'd say this is a duplicate of: "Add possibility to customize unsplash url" #4 – And any contribution there is much appreciated. :)

Also a tip from there: You can already edit the URL manually in the .css file for now. :)

**Comment by Ludovicis** [comment]
Thanks i have do that :)

**Comment by jancborchardt** [comment]
@Ludovicis yes, that’s good! :) Let’s please continue the discussion in #4, and feel free to open a pull request for this
