### ISSUE TITLE
Ability to disable background image in header

### ISSUE THREAD

**Issue by CHazz** [jancborchardt/unsplash#14]
any settings for disable texture in menu ?

**Comment by fa-ribeiro** [comment]
background images in the header are making app icons almost invisible:

<img width="434" alt="screen shot 2018-04-13 at 00 05 42" src="https://user-images.githubusercontent.com/2636096/38708497-73ca94c4-3eae-11e8-88d8-8b86d0bc0daa.png">

<img width="544" alt="screen shot 2018-04-12 at 23 58 10" src="https://user-images.githubusercontent.com/2636096/38708278-6ac457d0-3ead-11e8-8821-969d62456e66.png">

Where is the search box?
<img width="236" alt="screen shot 2018-04-13 at 00 03 54" src="https://user-images.githubusercontent.com/2636096/38708450-3b8cdac2-3eae-11e8-9a13-0f308975529d.png">

**Comment by jancborchardt** [comment]
Ok, will look at it tomorrow. Likely fixed by:
- Upping the opacity to 0.9 or just full white.
- Adjusting the drop shadow
- Using a background-blend-mode to subdue the picture a bit

**Comment by fa-ribeiro** [comment]
Or you can just revert commit 3d80e750 :-)

**Comment by ravenstar** [comment]
This feature would be useful.

As a work-around I've applied the following CSS under the "Custom CSS" input on the "Theming" page;
`header div#header {
  background-blend-mode: difference;
}
ul#appmenu li:hover {
  background-color: rgba(0, 0, 0, 0.42);
}`

**Comment by agrudsky** [comment]
+1 for this option. I do not wish for Unsplash to change the header, I am only looking for the login background to be changed, This feature should not have made it into this release without an option to turn it off.

**Comment by auberginepop** [comment]
Not sure if this is the right place to mention it but I love the new unsplash headers.
Thanks jancborchardt!

**Comment by blubbsy** [comment]
i agree to the previous posters. i turned off unsplash until it is possible to opt out the unsplash headers.

**Comment by Larsene** [comment]
please, could you make an option to disable unsplash for the header ? For now, i had to turn off entirely unsplash on my NextCloud...

**Comment by jancborchardt** [comment]
Started a pull request for a setting to disable the header background at https://github.com/jancborchardt/unsplash/pull/16 – as I’m mainly a designer and not a developer, I asked for some help there. But it’s almost done and I’ll do a release right afterwards, additionally also with visibility enhancements for those who like the image in the header. :smiley:

**Comment by diplodata** [comment]
I'd really like to use the header background if/when it's made optional, but it should only using darker images that maintain contrast with the symbols.

**Comment by marius-wieschollek** [comment]
@jancborchardt If you want to, you can look at my pull request. It gives users and administrators the option to choose where images are being used.

**Comment by 11harveyj** [comment]
As my workaround I manually removed the CSS that was added in commit https://github.com/jancborchardt/unsplash/commit/3d80e7503dcdfdd65ff71412ecd94b55e43ef44d

**Comment by newhinton** [comment]
Closed because this was implemented in #18.
Will be in the next Release!
Thanks @marius-wieschollek !

**Comment by jancborchardt** [comment]
Yes, huge thanks to @marius-wieschollek and also to @newhinton! :) And sorry for the lateness on my part – I had some wrist/hand pain issues often and couldn’t work that much.

**Comment by aljawaid** [comment]
Where is the setting in Admin?  I'm using version 1.1.1 but cant find how to disable the header. NC13.0.6

**Comment by jancborchardt** [comment]
The new version is not released yet because we are thinking about what else to include. Thanks for the patience. :)
