### ISSUE TITLE
Nextcloud 14

### ISSUE THREAD

**Issue by ChristophWurst** [jancborchardt/unsplash#25]
Hey @jancborchardt,

please see https://github.com/orgs/nextcloud/projects/15#card-11847034 :wink: 

Thanks

**Comment by auberginepop** [comment]
That link returns a 404

**Comment by ChristophWurst** [comment]
@auberginepop sorry for the confusion. This is a semi-internal project board to check Nextcloud apps if they are compatible with Nextcloud 14 and it seems like the board is not set to be publicly accessible. I think only organization member can see it.

**Comment by jancborchardt** [comment]
The app works fine on Nextcloud 14 already, but I also opened a pull request to make it compatible with the then-upcoming 15. :)
https://github.com/jancborchardt/unsplash/pull/26

Or do you see any specific issues?

**Comment by ChristophWurst** [comment]
> Or do you see any specific issues?

Nope, was just making sure you tested it :)
