### ISSUE TITLE
Problem installing plugin

### ISSUE THREAD

**Issue by janarzz** [jancborchardt/unsplash#30]
Hey, i got this error, when i tryng download and install this plugin.
cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by marius-wieschollek** [comment]
This seems like a connection issue in the curl library. Do you have some kind of firewall in your network?

**Comment by janarzz** [comment]
Hmm..i tryng again and plugin install success..wierd..

**Comment by marius-wieschollek** [comment]
Great :+1:
