### ISSUE TITLE
Add Option to disable "header" background

### ISSUE THREAD

**Issue by GitHorst** [jancborchardt/unsplash#31]
It would be nice to have the option to only use this for the login screen. (Was it like that, earlier?)

Apart from the fact that showing a tiny stripe of an (albeit potentially beautiful ;)) image is kind of pointless, it also makes navigating the symbols in the header more difficult. Especially, bt not only, of the image contains a lot of white.

Thanks a lot for your work on this neat add-on! =)

**Comment by marius-wieschollek** [comment]
This will be in the next release. See #14

**Comment by GitHorst** [comment]
Thanks -- sorry for only looking at the open issues, my bad :/
