### ISSUE TITLE
Ability to disable background image in header for all users or by default

### ISSUE THREAD

**Issue by biva** [jancborchardt/unsplash#35]
Following https://github.com/jancborchardt/unsplash/issues/14 I'm very happy to be able to use Unsplash again: thank you :)

But the setting is not that obvious to find for the average user. Some of them don't even know what it is about. Would it be possible to disable background image in the header by default? And/Or to add a setting in the admin section of Settings, so that we could apply this setting for all users?

**Comment by biva** [comment]
To complete this question, even a manual parameter in config.ini or anywhere in a config file, would be a good workaround for me.
Thank you!

**Comment by marius-wieschollek** [comment]
In the admin settings you can find global settings for this in the "Theming" section.

**Comment by biva** [comment]
Oups! I missed it :( Thank you @marius-wieschollek ! And sorry for the non-relevant issue.
