### ISSUE TITLE
PHP syntax error

### ISSUE THREAD

**Issue by xenlo** [jancborchardt/unsplash#36]
Hi,
Since I updated unsplash, I get my nextcloud screwed up by a PHP syntax error.
I assume that this is because I didn't match the minimal PHP dependencies. (NextCloud 13 still support php5.6, Unsplash1.1.3 still support NextCloud version 13, but needs min v7.0 of PHP).

**Error**
```
PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /var/www/nextcloud/apps/unsplash/lib/Services/SettingsService.php on line 58
```

**Versions**
NextCloud
```
root@server:~#  grep version /var/www/nextcloud/config/config.php
  'version' => '13.0.8.2',
```

Unsplash
```
root@server:~# grep version /var/www/nextcloud/apps/unsplash/appinfo/info.xml
<?xml version="1.0"?>
    <version>1.1.3</version>
        <php min-version="7.0" />
        <nextcloud min-version="13" max-version="16"/>
```
PHP
```
root@sevrer:~# php -v
PHP 5.6.30-0+deb8u1 (cli) (built: Feb  8 2017 08:50:21)
```

**Comment by marius-wieschollek** [comment]
You are correct.
Support for a Nextcloud version does not mean that we also support that versions minimum system requirements. This is why the app specifies it's minimum requirements in the info.xml

PHP 5.6 is also no longer receiving security patches from the PHP developers so i would really recommend that you switch to one of the [current php versions](http://php.net/supported-versions.php) like PHP 7.2.

**Comment by jancborchardt** [comment]
@marius-wieschollek @newhinton now that Nextcloud 15 has been released for a bit longer, we could also think about increasing the min-version to 14?

**Comment by marius-wieschollek** [comment]
Nextcloud 13 will be EOL in February, so i think we can raise the minimum requirement for the next release.

**Comment by xenlo** [comment]
Sounds fair to me!

Let's make «_Stop procrastinate move to php7_» as good New Year's resolution. It leaves me a month to find the time to care about that. :-)

**Comment by jancborchardt** [comment]
Pull request to up the version is at https://github.com/jancborchardt/unsplash/pull/37 – please review :)
