### ISSUE TITLE
We couldn't find that photo

### ISSUE THREAD

**Issue by jdhirst1** [jancborchardt/unsplash#41]
Unsplash app now only shows "We could not find that photo" image.

![deepinscreenshot_select-area_20190125120810](https://user-images.githubusercontent.com/9157196/51761087-1cb22480-209a-11e9-8bd3-081bc9b0d4d4.png)

NextCloud 15.0.2
Unsplash 1.1.3

Is anyone else having this problem? It started yesterday.

**Comment by herrkirk** [comment]
Same here
Nextcloud 15.0.2
Unsplash 1.1.3

**Comment by newhinton** [comment]
See #40, duplicate

**Comment by binhndicts** [comment]
We got the problem again, once last night and once this morning

**Comment by jdhirst1** [comment]
@binhndicts Just tested it now, seems to be working fine for me. Are you still experiencing this issue now?

**Comment by Rav4s** [comment]
Same here with 20.0.4snap1. About 4 out of 5 refreshes show "we couldn't find that photo."

**Comment by ms158** [comment]
Same here  20.0.4

**Comment by ghovmand** [comment]
302 from http request
