### ISSUE TITLE
Changing options results in an error

### ISSUE THREAD

**Issue by AragurDEV** [jancborchardt/unsplash#46]
When I'm trying to change options in the "Theming" options, added by this app. It reports an Error and doesn't save the change.  
![Example](https://user-images.githubusercontent.com/11004008/52022840-f3aaed00-24fa-11e9-8c94-1987b4fbfb71.png)

**Comment by AragurDEV** [comment]
Also the following issue is also caused by the app:
![screenshot_20190131_015507](https://user-images.githubusercontent.com/11004008/52023033-d296cc00-24fb-11e9-997a-0b3879c8cc6b.png)

**Comment by jellykells** [comment]
Same issue here on the Nextcloud 15 Snap package.

**Comment by marius-wieschollek** [comment]
Can you please check the Nextcloud error log for details?

**Comment by jellykells** [comment]
@marius-wieschollek I'm not seeing anything relevant in the Nextcloud log.

**Comment by AragurDEV** [comment]
So my issue got fixed, after changing the protocol in the Nextcloud config to https only.

**Comment by jellykells** [comment]
@AragurDEV Ah, that's probably the problem for me as well. My Nextcloud server is behind a reverse proxy which terminates SSL.

**Comment by marius-wieschollek** [comment]
If you're running Nextcloud behind a proxy you need to make sure that Nextcloud is configured to trust that proxy.
The settings use a full url created by Nextcloud to save the settings. If Nextcloud is configured incorrectly this may not work.

**Comment by vc7ee** [comment]
![image](https://user-images.githubusercontent.com/38327267/58979778-56203c80-87be-11e9-9f71-4dbefc9a2f75.png)
I have trusted the proxy, using Traefik.

**Comment by marius-wieschollek** [comment]
Please don't take over closed tickets. If you need support please go to the forum.

**Comment by vc7ee** [comment]
@marius-wieschollek Would you suggest I'd open yet an another issue? Unfortunately forums just stay empty.
