### ISSUE TITLE
Bug: Cannot disable on header or login page

### ISSUE THREAD

**Issue by bedawi** [jancborchardt/unsplash#47]
![nextcloud-unsplash](https://user-images.githubusercontent.com/18646682/52779104-d1ab8180-3047-11e9-82cb-93d33c297d59.gif)

I am having this weird issue that I cannot disable unsplash in the config menu. It just sets error, but there is nothing in the Nextcloud log. Any ideas? - Thanks a lot.

Unsplash V 1.1.3

**Comment by marius-wieschollek** [comment]
Could this be a duplicate of #46 ? Are there any warnings from Nextcloud on the overview page?

**Comment by bedawi** [comment]
Moin Marius,

yes, its very likely that this is a duplicate since I am also using Nextcloud behind a reverse proxy. Please give me 1-2 days before you close this thread. In this time I will investigate that issue and post my findings here. Thanks.

**Comment by marius-wieschollek** [comment]
You can take a look at this [documentation](https://docs.nextcloud.com/server/15/admin_manual/configuration_server/reverse_proxy_configuration.html) to make sure Nextcloud behaves correctly behind an https offloading proxy.

**Comment by bedawi** [comment]
Marius, again many thanks for precisely pointing this out. And indeed, its the trusted proxy setting.

To users, who use docker and have set up nextcloud behind an nginx reverse-proxy: Your can get the internal ip-addresses of your containers with this command:

```
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' nginx-web
172.21.0.3
```

With this knowledge you can add this line to include the whole internal subnet as trusted proxies in nextcloud's config.php:

`  'trusted_proxies' => array('172.21.0.0/24'),`

After restarting your nextcloud container, this specific problem is solved.
